apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: xjelinekj/sarcoma-fasttrack-api
    newName: xjelinekj/sarcoma-fasttrack-api
    newTag: 1.1.1
  - name: xjelinekj/sarcoma-fasttrack-frontend
    newName: xjelinekj/sarcoma-fasttrack-frontend
    newTag: 1.1.16

patches:
  - target:
      group: polyfea.github.io
      version: v1alpha1
      kind: MicroFrontend
      name: sarcoma-fasttrack-frontend
    patch: |-
      - op: replace
        path: /spec/cacheBustingHash
        value: 1.1.16
