apiVersion: wac-fiit.github.io/v1alpha1
kind: Project
metadata:
  name: sarcoma-fasttrack
spec:
  title: "Sarcoma FastTrack"
  description: "Sarcoma referral workflow for clinicians and specialized centers. Supports case reports, articles, and center management."
  authors: "Jakub Jelínek, Peter Hubina"
  azureLink: "https://wac-hospital.westeurope.cloudapp.azure.com/fea/sarcoma-fasttrack"
  frontendRepoUrl: "https://github.com/jakubkoje/sarcoma-fasttrack-frontend"
  backendRepoUrl: "https://github.com/jakubkoje/sarcoma-fasttrack-api"
  gitopsRepoUrl: "https://github.com/jakubkoje/sarcoma-fasttrack-gitops"
