apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

images:
  - name: xjelinekj/sarcoma-fasttrack-api
    newName: xjelinekj/sarcoma-fasttrack-api # {"$imagepolicy": "wac-hospital:sarcoma-fasttrack-api:name"}
    newTag: latest # {"$imagepolicy": "wac-hospital:sarcoma-fasttrack-api:tag"}
  - name: xjelinekj/sarcoma-fasttrack-frontend
    newName: xjelinekj/sarcoma-fasttrack-frontend # {"$imagepolicy": "wac-hospital:sarcoma-fasttrack-frontend:name"}
    newTag: latest # {"$imagepolicy": "wac-hospital:sarcoma-fasttrack-frontend:tag"}
