apiVersion: polyfea.github.io/v1alpha1
kind: MicroFrontend
metadata:
  name: sarcoma-fasttrack-frontend
spec:
  frontendClass: md-shell
  cacheBustingHash: latest
  service:
    name: sarcoma-fasttrack-frontend
  modulePath: sarcoma-fasttrack.js
